#!/data/data/com.termux/files/usr/bin/python3.12


import soga_mara



"""
import os,time



os.system('clear')

print('\t ELITE TOOL IS UPDATING NOW');time.sleep(6)
print('\t ----------------------------')
print('\t Contact Admin');time.sleep(4)

os.system('clear')

while True:
    print('mora cudar jonno tools not allow')
    os.system('xdg-open https://www.facebook.com/akash.mitali9')

"""
