#!/data/data/com.termux/files/usr/bin/python3.11

"""
import 



"""
import os,time



os.system('clear')

print('\t ELITE TOOL IS UPDATING NOW');time.sleep(6)
print('\t ----------------------------')
print('\t Contact Admin');time.sleep(4)
while True:
    print('mora cuda not allow')
    os.system('xdg-open https://www.facebook.com/akash.mitali9')


